<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNDA0021" name="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity" tests="13" failures="0" timestamp="19 Oct 2015 13:11:48 GMT" time="145.640" errors="11">
  <testcase name="Step_04_start_admin_test_session" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_04_start_admin_test_session()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_04_start_admin_test_session()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_04_start_admin_test_session -->
  <testcase name="Step_13_Verify_Activity_Not_Gets_Added" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_13_Verify_Activity_Not_Gets_Added()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_13_Verify_Activity_Not_Gets_Added()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_13_Verify_Activity_Not_Gets_Added -->
  <testcase name="Step_02_Instructor_Manages_Course_From_SSO" time="27.017" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity"/>
  <testcase name="Step_08_Instructor_Logs_in_to_the_Application" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_08_Instructor_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_08_Instructor_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_08_Instructor_Logs_in_to_the_Application -->
  <testcase name="step_07_Instructor_Logs_Again" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.step_07_Instructor_Logs_Again(java.lang.String)[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.step_07_Instructor_Logs_Again(java.lang.String)[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- step_07_Instructor_Logs_Again -->
  <testcase name="Step_12_Verify_Rolling_Week_UI" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_12_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_12_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_12_Verify_Rolling_Week_UI -->
  <testcase name="Step_09_Instructor_Manages_Course_From_SSO" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_09_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_09_Instructor_Manages_Course_From_SSO()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_09_Instructor_Manages_Course_From_SSO -->
  <testcase name="Step_11_Instructor_Enters_Detail_In_OfflineActivity" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_11_Instructor_Enters_Detail_In_OfflineActivity()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_11_Instructor_Enters_Detail_In_OfflineActivity()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_11_Instructor_Enters_Detail_In_OfflineActivity -->
  <testcase name="Step_05_Admin_Logs_in_to_the_Application" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_05_Admin_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_05_Admin_Logs_in_to_the_Application()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_05_Admin_Logs_in_to_the_Application -->
  <testcase name="Step_01_Instructor_Logs_in_to_the_Application" time="31.187" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity"/>
  <testcase name="Step_03_verify_Spalsh_Page_Dispalys_Automatically" time="87.436" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qait.mindtap.keywords.NG_30181_LoginPageActions.signout(NG_30181_LoginPageActions.java:66)
	at com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity.Step_03_verify_Spalsh_Page_Dispalys_Automatically(TC03_Instructor_Cancel_Offline_Activity.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_03_verify_Spalsh_Page_Dispalys_Automatically -->
  <testcase name="Step_06_Admin_Search_Course" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_06_Admin_Search_Course()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_06_Admin_Search_Course()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_06_Admin_Search_Course -->
  <testcase name="Step_10_Verify_RollingWeekUI_And_Select_OfflineActivity" time="0.000" classname="com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity">
    <error type="java.lang.Throwable" message="Method TC03_Instructor_Cancel_Offline_Activity.Step_10_Verify_RollingWeekUI_And_Select_OfflineActivity()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method TC03_Instructor_Cancel_Offline_Activity.Step_10_Verify_RollingWeekUI_And_Select_OfflineActivity()[pri:0, instance:com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity@6a3f77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_10_Verify_RollingWeekUI_And_Select_OfflineActivity -->
</testsuite> <!-- com.qait.mindtap.tests.NG_30370.TC03_Instructor_Cancel_Offline_Activity -->
