<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LNDA0021" name="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course" tests="9" failures="0" timestamp="1 Oct 2015 11:11:14 GMT" time="85.853" errors="8">
  <testcase name="Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_05_Verify_Weeks_CurrentWeekIcon_Displays_Along_Month_and_Date -->
  <testcase name="Step_01_Student_Logs_in_to_the_Application" time="21.271" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course"/>
  <testcase name="Step_08_Verify_Rolling_Week_UI" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_08_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_08_Verify_Rolling_Week_UI()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_08_Verify_Rolling_Week_UI -->
  <testcase name="Step_02_Student_Registers_Course" time="64.582" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out after 30 seconds waiting for visibility of [[RemoteWebDriver: firefox on WINDOWS (34e112c8-2bca-4ccc-8618-21500dd01eef)] -&gt; css selector: .small_green_button]
Build info: version: &#039;2.46.0&#039;, revision: &#039;61506a4624b13675f24581e453592342b7485d71&#039;, time: &#039;2015-06-04 10:22:50&#039;
System info: host: &#039;LNDA0021&#039;, ip: &#039;10.161.237.22&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;x86&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_51&#039;
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=38.0.5, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=34e112c8-2bca-4ccc-8618-21500dd01eef, locationContextEnabled=true, webStorageEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 34e112c8-2bca-4ccc-8618-21500dd01eef">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out after 30 seconds waiting for visibility of [[RemoteWebDriver: firefox on WINDOWS (34e112c8-2bca-4ccc-8618-21500dd01eef)] -> css selector: .small_green_button]
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: 'LNDA0021', ip: '10.161.237.22', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_51'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{applicationCacheEnabled=true, rotatable=false, databaseEnabled=true, handlesAlerts=true, version=38.0.5, platform=WINDOWS, nativeEvents=false, acceptSslCerts=true, webdriver.remote.sessionid=34e112c8-2bca-4ccc-8618-21500dd01eef, locationContextEnabled=true, webStorageEnabled=true, browserName=firefox, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 34e112c8-2bca-4ccc-8618-21500dd01eef
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:80)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:229)
	at com.qait.mindtap.automation.utils.SeleniumWait.waitForElementToBeVisible(SeleniumWait.java:53)
	at com.qait.mindtap.automation.getpageobjects.GetPage.element(GetPage.java:107)
	at com.qait.mindtap.automation.getpageobjects.GetPage.element(GetPage.java:101)
	at com.qait.mindtap.automation.getpageobjects.GetPage.isElementDisplayed(GetPage.java:245)
	at com.qait.mindtap.keywords.NG_30104.NG_30181_ConfirmCourseInformationActions.student_Click_Continue_Button(NG_30181_ConfirmCourseInformationActions.java:21)
	at com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course.Step_02_Student_Registers_Course(NG_30181_TC05_Student_Launch_the_Course.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_02_Student_Registers_Course -->
  <testcase name="Step_07_verify_Splash_Page" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_07_verify_Splash_Page()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_07_verify_Splash_Page()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_07_verify_Splash_Page -->
  <testcase name="Step_07_Instructor_SignOut" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_07_Instructor_SignOut()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_07_Instructor_SignOut()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_07_Instructor_SignOut -->
  <testcase name="Step_03_Student_Launch_Course" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_03_Student_Launch_Course()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_03_Student_Launch_Course()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_03_Student_Launch_Course -->
  <testcase name="Step_04_verify_Spalsh_Page_Dispalys_Automatically" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_04_verify_Spalsh_Page_Dispalys_Automatically()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_04_verify_Spalsh_Page_Dispalys_Automatically()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_04_verify_Spalsh_Page_Dispalys_Automatically -->
  <testcase name="Step_06_Verify_Expand_Collapse_Functionality" time="0.000" classname="com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course">
    <error type="java.lang.Throwable" message="Method NG_30181_TC05_Student_Launch_the_Course.Step_06_Verify_Expand_Collapse_Functionality()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method NG_30181_TC05_Student_Launch_the_Course.Step_06_Verify_Expand_Collapse_Functionality()[pri:0, instance:com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course@837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1063)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:217)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:92)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- Step_06_Verify_Expand_Collapse_Functionality -->
</testsuite> <!-- com.qait.mindtap.tests.NG_30104.NG_30181_TC05_Student_Launch_the_Course -->
